// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  imports: [FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  messageInput = '';
  displayMessage = 'Hello World';

  onDisplayMessage(): void {
    this.displayMessage = this.messageInput;
  }
}

<main class="app">
  <div class="card">
    <h1>Message Display</h1>

    <div class="form-group">
      <label for="message-input">Message to Display</label>
      <input
        id="message-input"
        type="text"
        [(ngModel)]="messageInput"
        placeholder="Enter your message"
      />
    </div>

    <button type="button" class="btn-primary" (click)="onDisplayMessage()">
      Display Message
    </button>

    <h2 class="display">{{ displayMessage }}</h2>
  </div>
</main>

// react-app/src/App.tsx
import { useState } from 'react'
import './App.css'

function App() {
  const [messageInput, setMessageInput] = useState('')
  const [displayMessage, setDisplayMessage] = useState('Hello World')

  const handleDisplayMessage = () => {
    setDisplayMessage(messageInput)
  }

  return (
    <main className="app">
      <div className="card">
        <h1>Message Display</h1>

        <div className="form-group">
          <label htmlFor="message-input">Message to Display</label>
          <input
            id="message-input"
            type="text"
            value={messageInput}
            onChange={(e) => setMessageInput(e.target.value)}
            placeholder="Enter your message"
          />
        </div>

        <button type="button" className="btn-primary" onClick={handleDisplayMessage}>
          Display Message
        </button>

        <h2 className="display">{displayMessage}</h2>
      </div>
    </main>
  )
}

export default App
